spring.application.name=api-gateway


server.port =9090
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost


## Gateway Routes Configuration
#spring.cloud.gateway.routes[0].id=product-service
#spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**